[package]
name = "basic_algorithms"
version = "0.1.0"
authors = ["lee unseo <lee.unseo17@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
